In [1]:
import pandas as pd

In [8]:
path_004 = 'test.csv.csv' 
df_multiclass_test = pd.read_csv(path_004)
df_multiclass_test

       index                                               text
0          0        Очень хороший магазин и сотрудники приятный
1          1  Самый обычный продуктовый магазин.  Есть сыры,...
2          2                             Всё хорошо и комфортно
3          3  Маленький филиальчик, все необходимое есть. Дв...
4          4                  Плохо относятся к клиентам!!!!!\n
...      ...                                                ...
12162  12162           Персонал вежливый . Большой ассортимент
12163  12163  Скидки на сыры. Скидки на алкоголь. Приемлимые...
12164  12164  Рядом с домом, неплохая пятерочка, персонал хо...
12165  12165  Хороший магазин у дома. Кассиры приветливые. П...
12166  12166  Норм, но надо побольше сотрудников на доставку...

[12167 rows x 2 columns]

In [5]:
path_003 = 'train.csv.csv' #  'sample_submission.csv.csv'
df_multiclass_train = pd.read_csv(path_003)
df_multiclass_train

       rate                                               text
0         4  Очень понравилось. Были в начале марта  с соба...
1         5  В целом магазин устраивает.\nАссортимент позво...
2         5  Очень хорошо что открылась 5 ка, теперь не над...
3         3  Пятёрочка громко объявила о том как она заботи...
4         3  Тесно, вечная сутолока, между рядами трудно ра...
...     ...                                                ...
48660     5  Удобный, но маленький и ещё не обновили как др...
48661     2  Постоянно обман в цене,написанна сумма на акци...
48662     2  Очень хочется пожелать этому магазину стать та...
48663     5  Нравится ваш магазин, персонал одекватный, пор...
48664     3                                 Не очень  персонал

[48665 rows x 2 columns]

In [6]:
df_multiclass_train.describe()

               rate
count  48665.000000
mean       4.055666
std        1.273523
min        1.000000
25%        3.000000
50%        5.000000
75%        5.000000
max        5.000000

In [7]:
df_multiclass_train['rate'].value_counts()

rate
5    26069
4     9922
3     6126
1     4138
2     2410
Name: count, dtype: int64